name: volume_info
description: "Showing info about volumes"
version: 0.0.7
homepage: https://github.com/ssibitz/volume_info

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.freudenstrahl.volume_info
        pluginClass: VolumeInfoPlugin